### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by whitegolum** [DillyzThe1/DictatorRole#1]
Good work but it's kinda overpowerd , what if the Dictator get a button to activate during discussion that he use his x8 Vote , and that button can only be used twice per game so the Dictator wouldn't be tossing people left and right + it make more sense for him to use his vote wisely ? when he doesn't click on the button his vote count as normal like everyone else ?

**Comment by DillyzThe1** [comment]
while i dont know how to make a new button instance for the voting buttons, let alone a textured button in general, i could try a keybind to toggle it. this on/off toggle would be shown under the ping counter.
also, i am making a 1.1 update for the option to set his voting value. 
will try to add this soon, thanks!
